steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'package', '-DskipTests']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ridewarriors-2552b/ridewarriors-backend', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ridewarriors-2552b/ridewarriors-backend']

images:
- 'gcr.io/ridewarriors-2552b/ridewarriors-backend'


